import type { Character } from "@/lib/types";

const NOW = "2026-05-01T00:00:00.000Z";

function makeMock(partial: Partial<Character> & Pick<Character, "id" | "name">): Character {
  return {
    owner_id: "mock",
    session_id: null,
    class: "",
    race: "",
    level: 1,
    hp: 10,
    max_hp: 10,
    temp_hp: 0,
    ac: 10,
    initiative: 0,
    speed: 9,
    xp: 0,
    xp_next_level: 300,
    gold: 0,
    conditions: [],
    death_saves: { successes: 0, failures: 0 },
    stats: {
      strength: 10,
      dexterity: 10,
      constitution: 10,
      intelligence: 10,
      wisdom: 10,
      charisma: 10,
    },
    skills: {},
    inventory: [],
    spells: [],
    backstory: "",
    notes: "",
    avatar_url: null,
    ai_summary: "",
    created_at: NOW,
    updated_at: NOW,
    ...partial,
  };
}

export const MOCK_PLAYERS: Character[] = [
  makeMock({
    id: "mock-1",
    name: "Thorin Pedraforte",
    class: "Bárbaro",
    race: "Anão",
    level: 5,
    hp: 48,
    max_hp: 52,
    ac: 16,
    stats: { strength: 18, dexterity: 12, constitution: 16, intelligence: 8, wisdom: 12, charisma: 10 },
    backstory: "Filho exilado do clã Pedraforte, busca redenção em batalha.",
  }),
  makeMock({
    id: "mock-2",
    name: "Elaria Folhaprata",
    class: "Maga",
    race: "Elfa",
    level: 4,
    hp: 22,
    max_hp: 26,
    ac: 13,
    stats: { strength: 8, dexterity: 14, constitution: 12, intelligence: 18, wisdom: 13, charisma: 11 },
    conditions: ["concentrando"],
  }),
  makeMock({
    id: "mock-3",
    name: "Rorick Sombramanta",
    class: "Ladino",
    race: "Halfling",
    level: 5,
    hp: 8,
    max_hp: 36,
    ac: 15,
    stats: { strength: 10, dexterity: 18, constitution: 12, intelligence: 13, wisdom: 11, charisma: 14 },
    conditions: ["envenenado", "atordoado"],
  }),
  makeMock({
    id: "mock-4",
    name: "Sister Mira",
    class: "Clériga",
    race: "Humana",
    level: 5,
    hp: 38,
    max_hp: 42,
    ac: 18,
    stats: { strength: 12, dexterity: 10, constitution: 14, intelligence: 11, wisdom: 18, charisma: 13 },
  }),
  makeMock({
    id: "mock-5",
    name: "Kael",
    class: "Paladino",
    race: "Tiefling",
    level: 6,
    hp: 0,
    max_hp: 54,
    ac: 19,
    death_saves: { successes: 1, failures: 2 },
    stats: { strength: 16, dexterity: 10, constitution: 14, intelligence: 10, wisdom: 12, charisma: 16 },
  }),
];
