import type { Background } from "./types";

export const BACKGROUNDS: Background[] = [
  {
    id: "acolito",
    name: "Acólito",
    skills: ["Intuição", "Religião"],
    languages: 2,
    equipment: [
      "Símbolo sagrado",
      "Livro de orações",
      "5 varetas de incenso",
      "Vestes",
      "Roupas comuns",
    ],
    gold: 15,
    visualDetail: "small holy symbol pendant visible at the chest, serene expression",
    feature: "Refúgio dos Fiéis",
    featureDesc:
      "Você e seus companheiros podem receber cura e cuidados gratuitos em templos da sua fé.",
    personalityTraits: [
      "Cito passagens sagradas em quase todas as conversas.",
      "Sou tolerante com outras fés e respeito o caminho alheio.",
      "Vi tanta coisa que pouco me surpreende.",
      "Falo com calma, escolhendo cada palavra.",
      "Tenho um trauma religioso que escondo bem.",
      "Vejo presságios em qualquer evento incomum.",
      "Sou rápido em julgar quem se desvia do dogma.",
      "Tenho um humor seco que descontrai os irmãos.",
    ],
    ideals: [
      "Tradição. As tradições antigas precisam ser preservadas.",
      "Caridade. Devo ajudar os necessitados.",
      "Mudança. As tradições mortas devem dar lugar ao novo.",
      "Poder. Subirei na hierarquia da fé.",
      "Fé. Confio que minha divindade guiará meus passos.",
      "Aspiração. Desejo provar que sou digno do meu chamado.",
    ],
    bonds: [
      "Devo a vida ao sacerdote que me criou.",
      "Tudo o que faço, faço pelo povo comum.",
      "Morrerei para recuperar uma relíquia perdida.",
      "Vingarei o templo destruído pelos hereges.",
      "Procuro encontrar quem inspirou minha fé.",
      "Possuo um livro sagrado que devo proteger.",
    ],
    flaws: [
      "Julgo os outros com severidade — e a mim ainda mais.",
      "Confio cegamente nos superiores da minha fé.",
      "Os textos sagrados são infalíveis.",
      "Sou inflexível com quem desafia minha fé.",
      "Tenho dificuldade em demonstrar afeto.",
      "Coloquei a fé acima da família.",
    ],
  },
  {
    id: "artesao-guilda",
    name: "Artesão de Guilda",
    skills: ["Intuição", "Persuasão"],
    tools: ["Ferramentas de artesão"],
    languages: 1,
    equipment: [
      "Ferramentas de artesão",
      "Carta de apresentação da guilda",
      "Roupas de viagem",
    ],
    gold: 15,
    visualDetail:
      "guild medallion at the belt, calloused hands marked by craft",
    feature: "Membro da Guilda",
    featureDesc:
      "Sua guilda oferece abrigo, contatos e suporte legal em qualquer cidade onde tenha sede.",
    personalityTraits: [
      "Acredito que tudo que vale a pena fazer, vale a pena fazer direito.",
      "Sou pomposo ao falar do meu ofício.",
      "Sempre ofereço meus serviços antes de pedir favores.",
      "Estou cheio de provérbios e ditados antigos.",
      "Sou perdulário com dinheiro suado.",
      "Trato meus aprendizes com rigor severo.",
      "Não confio em forasteiros logo de cara.",
      "Acolho qualquer um que aprecie boa cerveja.",
    ],
    ideals: [
      "Comunidade. Preciso cuidar dos que dependem do meu ofício.",
      "Generosidade. Minhas obras enriquecem o mundo.",
      "Liberdade. Ninguém deveria ser preso por dívidas.",
      "Maestria. Quero ser o melhor da minha guilda.",
      "Ganância. Existo para acumular fortuna.",
      "Pessoas. Sou leal aos meus colegas, não às regras.",
    ],
    bonds: [
      "Honro o instrumento que recebi do meu mestre.",
      "Construí algo duradouro e quero que perdure.",
      "Devo dinheiro a uma guilda rival e fugi.",
      "Minha família depende do que envio.",
      "Sigo viajando para aperfeiçoar meu ofício.",
      "Quero que meu nome figure entre os grandes.",
    ],
    flaws: [
      "Levo demais a sério qualquer crítica ao meu trabalho.",
      "Sou ganancioso ao extremo.",
      "Sou inflexível quanto às regras da guilda.",
      "Vejo trapaça em qualquer competidor.",
      "Coloco o ofício acima da família.",
      "Não consigo guardar segredos comerciais.",
    ],
  },
  {
    id: "artista",
    name: "Artista",
    skills: ["Acrobacia", "Atuação"],
    tools: ["Kit de disfarce", "Um instrumento musical"],
    equipment: [
      "Instrumento musical",
      "Adereço favorito",
      "Roupas de artista",
    ],
    gold: 15,
    visualDetail:
      "expressive eyes with a hint of greasepaint, a small charm at the wrist",
    feature: "Por Demanda Popular",
    featureDesc:
      "Você sempre encontra hospedagem e comida em troca de uma performance.",
    personalityTraits: [
      "Sei uma história para cada situação.",
      "Sempre sei o tom certo a entoar.",
      "Conheço todas as fofocas da cidade.",
      "Mudo de plano com facilidade espantosa.",
      "Adoro chamar atenção em qualquer cômodo.",
      "Cito poesias com frequência.",
      "Apaixono-me com facilidade absurda.",
      "Tenho uma piada para cada ocasião.",
    ],
    ideals: [
      "Beleza. A vida sem arte não vale ser vivida.",
      "Tradição. Mantenho viva a memória dos antigos.",
      "Criatividade. O mundo cabe na minha próxima obra.",
      "Generosidade. Minha arte deve elevar os outros.",
      "Honestidade. Arte sem verdade não é arte.",
      "Fama. Quero meu nome eternizado.",
    ],
    bonds: [
      "Meu instrumento é minha posse mais querida.",
      "Alguém roubou meu maior trabalho.",
      "Quero ser celebrado por minha geração.",
      "Idolatrolo um herói da arte.",
      "Apaixonei-me por um nobre inalcançável.",
      "Ofendi alguém poderoso e estou em fuga.",
    ],
    flaws: [
      "Faria qualquer coisa para evitar trabalho honesto.",
      "Sou amaldiçoadamente vaidoso.",
      "Confunde-se palco e realidade às vezes.",
      "Caio em qualquer rosto bonito.",
      "Acredito sempre estar certo.",
      "Desprezo quem não aprecia arte.",
    ],
  },
  {
    id: "charlatao",
    name: "Charlatão",
    skills: ["Enganação", "Prestidigitação"],
    tools: ["Kit de disfarce", "Kit de falsificação"],
    equipment: [
      "Roupas finas",
      "Kit de disfarce",
      "Ferramentas do golpe",
    ],
    gold: 15,
    visualDetail:
      "a cunning glint in the eye, slightly too-fancy clothes for a vagabond",
    feature: "Identidade Falsa",
    featureDesc:
      "Você possui uma segunda identidade documentada e pode forjar credenciais simples.",
    personalityTraits: [
      "Caio em qualquer plano de ficar rico rápido.",
      "Tenho uma piada nova toda semana.",
      "Falo demais e me complico.",
      "Mudo de identidade conforme a plateia.",
      "Inventei um sotaque convincente.",
      "Vivo bajulando os ricos.",
      "Disfarço meus medos com bravata.",
      "Tenho um truque preferido para tudo.",
    ],
    ideals: [
      "Independência. Detesto regras de qualquer espécie.",
      "Justiça. Só engano quem merece.",
      "Caridade. Roubo dos ricos para dar aos pobres.",
      "Criatividade. Cada golpe é uma obra de arte.",
      "Amizade. Lealdade, não dinheiro, é o que importa.",
      "Aspiração. Pretendo ascender e mudar de classe.",
    ],
    bonds: [
      "Devo um favor a alguém perigoso.",
      "Procuro vingar um amor traído.",
      "Tenho um filho secreto que protejo.",
      "Roubei do alvo errado e estou marcado.",
      "Quero limpar meu nome de um crime que não cometi.",
      "Sustento uma família de órfãos com meus golpes.",
    ],
    flaws: [
      "Não consigo resistir a uma cara bonita.",
      "Me apaixono por quem está enganando.",
      "Sou viciado em jogos de azar.",
      "Não confio em ninguém — nem em mim.",
      "Sempre tento o golpe maior do que devia.",
      "Mantenho duas vidas e elas vão colidir.",
    ],
  },
  {
    id: "criminoso",
    name: "Criminoso",
    skills: ["Enganação", "Furtividade"],
    tools: ["Um conjunto de jogos", "Ferramentas de ladrão"],
    equipment: [
      "Pé de cabra",
      "Roupas escuras com capuz",
      "Bolsa com 15 po",
    ],
    gold: 15,
    visualDetail:
      "a faint criminal brand or tattoo half-hidden by a sleeve",
    feature: "Contato Criminoso",
    featureDesc:
      "Você tem um contato confiável que liga você ao submundo em qualquer cidade.",
    personalityTraits: [
      "Sempre tenho um plano caso as coisas dêem errado.",
      "Sou frio e sereno mesmo sob pressão.",
      "Aguardo a oportunidade certa em silêncio.",
      "Não confio em ninguém à primeira vista.",
      "Trato todos como peças num jogo.",
      "Sou rápido com a língua e com a faca.",
      "Disfarço minhas emoções como reflexo.",
      "Aposto pelo prazer do risco.",
    ],
    ideals: [
      "Honra. Não traio quem trabalha comigo.",
      "Liberdade. Cadeias são para os tolos.",
      "Caridade. Roubo para alimentar os meus.",
      "Ganância. Ouro é o único deus.",
      "Pessoas. Minha gangue é minha família.",
      "Redenção. Há bondade em mim ainda.",
    ],
    bonds: [
      "Preciso pagar uma dívida com um gângster.",
      "Meu irmão depende dos meus crimes.",
      "Minha gangue foi destruída e quero vingança.",
      "Roubei algo que não posso devolver.",
      "Procuro proteger um inocente.",
      "Quero deixar essa vida — de verdade.",
    ],
    flaws: [
      "Sempre fujo quando a coisa aperta.",
      "Sou viciado em adrenalina.",
      "Não consigo resistir a um cofre cheio.",
      "Trato meus parceiros como descartáveis.",
      "Bebo demais para esquecer.",
      "Confio rápido demais em quem não devia.",
    ],
  },
  {
    id: "eremita",
    name: "Eremita",
    skills: ["Medicina", "Religião"],
    tools: ["Kit de herbalismo"],
    languages: 1,
    equipment: [
      "Estojo de pergaminhos",
      "Coberta de inverno",
      "Roupas comuns",
      "Kit de herbalismo",
    ],
    gold: 5,
    visualDetail:
      "unkempt beard and hair, weathered hands, simple monastic look",
    feature: "Descoberta",
    featureDesc:
      "Você descobriu uma verdade poderosa durante seu isolamento.",
    personalityTraits: [
      "Falo pouco mas penso muito antes de cada palavra.",
      "Estou estranho em meio a multidões.",
      "Vivo em silêncio prolongado por dias.",
      "Tenho um pet predileto da natureza.",
      "Vejo significado em coincidências comuns.",
      "Costumo desaparecer sem aviso.",
      "Carrego sempre um amuleto da minha solidão.",
      "Conheço cada planta da floresta por nome.",
    ],
    ideals: [
      "Maior bem. Meu sacrifício pode salvar muitos.",
      "Lógica. Devo encontrar a razão de tudo.",
      "Inspiração. Minha descoberta servirá ao mundo.",
      "Auto-conhecimento. Quem é só si mesmo é livre.",
      "Sem outro. Meu retiro é meu único caminho.",
      "Liberdade. Renunciei a tudo o que escraviza.",
    ],
    bonds: [
      "Descobri algo que devo proteger a todo custo.",
      "Meu retiro foi destruído e quero recuperá-lo.",
      "Procuro um discípulo digno do que aprendi.",
      "Devo a vida a um animal que me salvou.",
      "Anseio retornar ao meu retiro um dia.",
      "Sou guardião de um segredo perigoso.",
    ],
    flaws: [
      "Sou crítico das fraquezas dos demais.",
      "Tenho dificuldade em conviver em sociedade.",
      "Pensei demais e agora não consigo agir.",
      "Sou rígido em meus rituais diários.",
      "Falo aos outros como se fossem alunos.",
      "Confio cegamente nos meus instintos.",
    ],
  },
  {
    id: "forasteiro",
    name: "Forasteiro",
    skills: ["Atletismo", "Sobrevivência"],
    tools: ["Um instrumento musical"],
    languages: 1,
    equipment: [
      "Bordão",
      "Armadilha de caça",
      "Troféu de animal",
      "Roupas de viagem",
    ],
    gold: 10,
    visualDetail:
      "weather-burned skin, a small bone trinket, sturdy traveling boots",
    feature: "Memorável",
    featureDesc:
      "Você sempre encontra abrigo, comida e água nas terras selvagens.",
    personalityTraits: [
      "Estou sempre olhando para o horizonte.",
      "Falo pouco mas observo muito.",
      "Carrego uma cicatriz feita por uma fera.",
      "Tenho um par sentimento profundo pela natureza.",
      "Sou supersticioso com as fases da lua.",
      "Saúdo cada manhã como uma vitória.",
      "Conheço os nomes das estrelas.",
      "Trato todo lugar como se fosse passagem.",
    ],
    ideals: [
      "Mudança. Tudo precisa mudar para sobreviver.",
      "Vida. A natureza é sagrada.",
      "Honra. Não fujo de uma luta justa.",
      "Maior bem. Cada vida importa.",
      "Liberdade. Ninguém me prende a nada.",
      "Glória. Quero ser lembrado pelos meus feitos.",
    ],
    bonds: [
      "Minha família foi assassinada e busco vingança.",
      "Tenho um animal companheiro inseparável.",
      "Quero proteger as terras onde nasci.",
      "Sou o último da minha tribo.",
      "Carrego um totem ancestral.",
      "Procuro uma terra perdida que sonhei.",
    ],
    flaws: [
      "Não confio em nada feito de pedra.",
      "Solto a fúria primeiro, penso depois.",
      "Tenho medo profundo de cidades.",
      "Sou supersticioso ao extremo.",
      "Guardo rancor por muito tempo.",
      "Me afasto quando alguém se aproxima.",
    ],
  },
  {
    id: "heroi-povo",
    name: "Herói do Povo",
    skills: ["Adestrar Animais", "Sobrevivência"],
    tools: ["Ferramentas de artesão", "Veículos terrestres"],
    equipment: [
      "Ferramentas de artesão",
      "Pá",
      "Pote de ferro",
      "Roupas comuns",
    ],
    gold: 10,
    visualDetail:
      "a humble peasant token at the neck, simple sturdy hands",
    feature: "Hospitalidade Rústica",
    featureDesc:
      "Plebeus o aceitam, escondem e ajudam quando necessário.",
    personalityTraits: [
      "Julgo as pessoas pelas ações, não palavras.",
      "Falo simples mas direto ao ponto.",
      "Lido com tudo com calma serena.",
      "Conto longas histórias sobre minha aldeia.",
      "Sou tímido em meio a nobres.",
      "Confio nos amigos mais que em provas.",
      "Sempre divido comida com quem precisa.",
      "Sonho com uma vida tranquila no campo.",
    ],
    ideals: [
      "Respeito. Pessoas merecem dignidade.",
      "Justiça. Os fortes não devem oprimir os fracos.",
      "Liberdade. Tiranos não podem governar para sempre.",
      "Maior bem. Sirvo aos meus em primeiro lugar.",
      "Sinceridade. Dizer a verdade é meu caminho.",
      "Destino. Nasci para algo grande.",
    ],
    bonds: [
      "Trabalho a terra que pertencia ao meu pai.",
      "Defendo minha aldeia onde quer que esteja.",
      "Sou apaixonado por alguém que ficou para trás.",
      "Possuo uma relíquia da família que preservo.",
      "Devo provar meu valor aos que duvidaram.",
      "Vou recompensar o nobre que me ajudou.",
    ],
    flaws: [
      "Confronto qualquer tirano sem pensar.",
      "Sou ingênuo quanto à corrupção das cidades.",
      "Tenho preconceito contra nobres.",
      "Acredito demais nos próprios mitos.",
      "Sou teimoso ao extremo.",
      "Trato problemas com força bruta.",
    ],
  },
  {
    id: "marinheiro",
    name: "Marinheiro",
    skills: ["Atletismo", "Percepção"],
    tools: ["Equipamento de navegador", "Veículos aquáticos"],
    equipment: [
      "Marlinespike (gancho)",
      "Roupas comuns",
      "Bolsa com 10 po",
    ],
    gold: 10,
    visualDetail:
      "nautical tattoo across forearm, salt-bleached hair, weathered ropes at the belt",
    feature: "Passagem de Navio",
    featureDesc:
      "Você consegue passagem gratuita em navios mercantes em troca de trabalho.",
    personalityTraits: [
      "Pratico um humor de marinheiro com todos.",
      "Conheço cada nó e cada cordame.",
      "Tenho cicatrizes do mar que mostro com orgulho.",
      "Bebo mais do que devia em terra firme.",
      "Falo gírias náuticas mesmo em terra seca.",
      "Sou generoso com colegas, duro com terráqueos.",
      "Tenho uma canção de mar para cada situação.",
      "Acredito em sereias.",
    ],
    ideals: [
      "Respeito. O capitão é a lei do navio.",
      "Justiça. Piratas devem ser caçados.",
      "Liberdade. O mar é a única pátria livre.",
      "Maestria. Quero ser o melhor navegador.",
      "Pessoas. A tripulação é família.",
      "Aspiração. Comandarei meu próprio navio.",
    ],
    bonds: [
      "Sou leal ao meu capitão até a morte.",
      "Tripulação massacrada por piratas — vingança jurada.",
      "Procuro um tesouro perdido descrito num mapa.",
      "Tenho família em um porto distante.",
      "Quero comprar meu próprio navio.",
      "Devo dinheiro a um almirante corrupto.",
    ],
    flaws: [
      "Bebo até desmaiar em qualquer porto.",
      "Falo demais com estranhos.",
      "Acredito em qualquer rumor de tesouro.",
      "Brigo por qualquer ofensa pequena.",
      "Tenho medo de morrer afogado.",
      "Não respeito autoridade em terra firme.",
    ],
  },
  {
    id: "nobre",
    name: "Nobre",
    skills: ["História", "Persuasão"],
    tools: ["Um conjunto de jogos"],
    languages: 1,
    equipment: [
      "Roupas finas",
      "Anel com selo de família",
      "Pergaminho com genealogia",
      "Bolsa com 25 po",
    ],
    gold: 25,
    visualDetail:
      "a discreet signet ring, finely-tailored seam at the collar",
    feature: "Posição de Privilégio",
    featureDesc:
      "Plebeus o tratam com deferência. Nobres o aceitam como par.",
    personalityTraits: [
      "Levo o decoro a sério em qualquer ocasião.",
      "Cito o lema da minha família com frequência.",
      "Trato comuns com cortesia distante.",
      "Aprecio belas artes acima de tudo.",
      "Sou refinado nos meus gostos.",
      "Sou condescendente com quem trabalha.",
      "Mantenho minhas vestes impecáveis.",
      "Quero retomar honra perdida pela família.",
    ],
    ideals: [
      "Respeito. Posição obriga deveres.",
      "Responsabilidade. Devo zelar pelos meus súditos.",
      "Independência. Quero romper as obrigações.",
      "Poder. Subirei no escalão da nobreza.",
      "Família. A linhagem está acima de tudo.",
      "Nobreza obriga. Devo dar o exemplo.",
    ],
    bonds: [
      "Vou recuperar o título perdido pela minha casa.",
      "Sou leal ao meu povo, não à coroa.",
      "Tenho um irmão que rivaliza comigo.",
      "Devo retornar antes do fim do ano.",
      "Mantenho um amor secreto além do meu posto.",
      "Procuro vingança por uma traição contra minha casa.",
    ],
    flaws: [
      "Confio cegamente na palavra de nobres.",
      "Trato plebeus com desprezo.",
      "Sou orgulhoso ao ponto de quebrar antes de ceder.",
      "Tenho um vício luxuoso que esgota fortunas.",
      "Sou ingênuo quanto a perigos reais.",
      "Mantenho rancores antigos por gerações.",
    ],
  },
  {
    id: "orfao",
    name: "Órfão",
    skills: ["Furtividade", "Sobrevivência"],
    tools: ["Kit de disfarce", "Ferramentas de ladrão"],
    equipment: [
      "Faca pequena",
      "Mapa da cidade onde cresceu",
      "Boneco de pano",
      "Roupas comuns",
    ],
    gold: 10,
    visualDetail:
      "thin frame, watchful eyes, a small token from the streets at the wrist",
    feature: "Segredos da Cidade",
    featureDesc:
      "Você conhece atalhos e passagens secretas em cidades.",
    personalityTraits: [
      "Escondo comida pelos bolsos por hábito.",
      "Não confio em ninguém à primeira vista.",
      "Tenho um humor amargo e seco.",
      "Carrego um boneco da infância.",
      "Aceito qualquer trabalho honesto.",
      "Defendo crianças com fúria animal.",
      "Tenho um sorriso que esconde tudo.",
      "Conheço cada rua daquela cidade.",
    ],
    ideals: [
      "Respeito. Todos merecem dignidade.",
      "Comunidade. Crianças de rua são minha família.",
      "Mudança. As ruas precisam ser limpas.",
      "Independência. Cuido de mim mesmo.",
      "Aspiração. Sairei desta vida por cima.",
      "Caridade. Compartilho o pouco que tenho.",
    ],
    bonds: [
      "Procuro a família que perdi em criança.",
      "Defendo a quadrilha que me criou.",
      "Tenho um irmão de criação que devo encontrar.",
      "Vingarei a morte do meu mentor das ruas.",
      "Quero pagar a dívida dos que me alimentaram.",
      "Tenho uma relíquia dos meus pais.",
    ],
    flaws: [
      "Roubo por hábito mesmo sem precisar.",
      "Confio rápido em qualquer figura paterna.",
      "Não suporto ficar fechado em quartos pequenos.",
      "Estoco comida obsessivamente.",
      "Tenho medo de me apegar a alguém.",
      "Resolvo conflitos com a faca.",
    ],
  },
  {
    id: "sabio",
    name: "Sábio",
    skills: ["Arcanismo", "História"],
    languages: 2,
    equipment: [
      "Vidro de tinta preta",
      "Pena",
      "Faca pequena",
      "Carta de um colega falecido",
      "Roupas comuns",
    ],
    gold: 10,
    visualDetail:
      "ink-stained fingers, spectacles or thoughtful gaze, a tucked scroll",
    feature: "Pesquisador",
    featureDesc:
      "Quando precisa de informação, sabe onde e como obtê-la.",
    personalityTraits: [
      "Cito autores antigos em qualquer debate.",
      "Sou pedante até com amigos próximos.",
      "Tomo notas de tudo que vejo.",
      "Falo devagar e com precisão.",
      "Esqueço comer quando estudo.",
      "Sou irritadiço com ignorância proposital.",
      "Comparo cada problema com algo lido.",
      "Carrego sempre um livro favorito.",
    ],
    ideals: [
      "Conhecimento. Saber é o caminho da liberdade.",
      "Beleza. A verdade da arte vale mais que ouro.",
      "Lógica. Emoções obscurecem a razão.",
      "Sem limites. Nada deve restringir o saber.",
      "Poder. Conhecer é dominar.",
      "Auto-aperfeiçoamento. Estudo para crescer.",
    ],
    bonds: [
      "Procuro um manuscrito perdido há séculos.",
      "Devo proteger meus alunos a todo custo.",
      "Quero superar o mestre que me humilhou.",
      "Carrego uma teoria que mudará tudo.",
      "Devo derrotar uma sociedade rival.",
      "Tenho um livro que jamais pode ser lido.",
    ],
    flaws: [
      "Sou arrogante com quem sabe menos.",
      "Confio só em fontes escritas.",
      "Sou facilmente distraído por mistérios.",
      "Falo de mais sobre temas obscuros.",
      "Subestimo perigos físicos.",
      "Mantenho segredos perigosos com má conduta.",
    ],
  },
  {
    id: "soldado",
    name: "Soldado",
    skills: ["Atletismo", "Intimidação"],
    tools: ["Um conjunto de jogos", "Veículos terrestres"],
    equipment: [
      "Insígnia de patente",
      "Troféu de inimigo derrotado",
      "Conjunto de dados",
      "Roupas comuns",
    ],
    gold: 10,
    visualDetail:
      "a faded scar across the face, military bearing, regiment patch on sleeve",
    feature: "Patente Militar",
    featureDesc:
      "Soldados leais à sua antiga unidade ainda reconhecem sua autoridade.",
    personalityTraits: [
      "Sou direto, sem rodeios, mesmo em conversa fina.",
      "Sigo cada ordem com precisão.",
      "Tenho uma cicatriz que conto a história.",
      "Mantenho minhas armas impecáveis.",
      "Falo em jargão militar mesmo fora de ordem.",
      "Disfarço o trauma com bravura.",
      "Sou supersticioso com talismãs de guerra.",
      "Tenho um humor sombrio sobre a morte.",
    ],
    ideals: [
      "Maior bem. Servi por proteção dos inocentes.",
      "Responsabilidade. Cumpro minha missão.",
      "Independência. Sirvo se a causa for justa.",
      "Poder. A vitória pertence aos fortes.",
      "Vida. Cada soldado salvo importa.",
      "Honra. Minha palavra é meu escudo.",
    ],
    bonds: [
      "Daria a vida pelos que serviram comigo.",
      "Tenho uma promessa de retornar para casa.",
      "Vingarei meus camaradas mortos em batalha.",
      "Carrego uma medalha sagrada do meu pelotão.",
      "Devo proteger uma criança que minha unidade resgatou.",
      "Procuro o oficial que nos traiu.",
    ],
    flaws: [
      "Obedeço ordens mesmo quando são erradas.",
      "Tenho dificuldade em confiar em civis.",
      "Bebo para esquecer pesadelos.",
      "Resolvo desentendimentos com a espada.",
      "Não suporto fraqueza visível.",
      "Mantenho rancor por traições antigas.",
    ],
  },
] as const;
