// Facções, gangues e forças da lei (Doc 2 §14, pp. 258–266).
// Templates disponíveis, não encontros obrigatórios. "Dedo Furioso" e "Artes Marciais"
// não têm verbete nas 30 habilidades de PJ — ficam em habilidadesPendentes (lacuna G21),
// nunca oferecidas como habilidade jogável.

import type { SacramentoFaction } from "./types";

export const SACRAMENTO_FACTIONS: SacramentoFaction[] = [
  {
    id: "curupira",
    emblema: "/story/factions/curupira.webp",
    nome: "Gangue do Curupira",
    categoria: "gangue",
    resumo: "Atua na Floresta do Cipó; emboscadas silenciosas.",
    membros: [
      { papel: "Gritos", tipo: "comum", ndc: "2–3", habilidades: [], paginas: [259] },
      {
        papel: "Silêncios",
        tipo: "especial",
        ndc: "2–4",
        habilidades: ["Armas da Natureza", "Ataque Sacana"],
        paginas: [259],
      },
    ],
    paginas: [259],
  },
  {
    id: "bandoleira-escarlate",
    emblema: "/story/factions/bandoleira-escarlate.webp",
    nome: "Bandoleira Escarlate",
    categoria: "gangue",
    resumo: "Hierarquia por cores, liderada pelo Escarlate.",
    membros: [
      { papel: "Rosáceos", tipo: "comum", ndc: "1–3", habilidades: [], paginas: [260] },
      { papel: "Rubros", tipo: "comum", ndc: "4–5", habilidades: [], paginas: [260] },
      {
        papel: "Vermelhos",
        tipo: "especial",
        ndc: "1–3",
        habilidades: ["Dedo Quente", "Escudo Humano"],
        paginas: [260],
      },
      {
        papel: "O Escarlate",
        tipo: "especial",
        ndc: "6",
        habilidades: ["Ameaça Covarde", "Marretada", "Mestre Arsenal", "Parrudeza"],
        paginas: [260],
      },
    ],
    paginas: [260],
  },
  {
    id: "seis-balas",
    emblema: "/story/factions/seis-balas.webp",
    nome: "Comando das Seis Balas",
    categoria: "gangue",
    resumo: "Crime organizado de Belo Horizonte, do batedor ao chefão.",
    membros: [
      { papel: "Correria", tipo: "comum", ndc: "2", habilidades: [], paginas: [261] },
      { papel: "Bacana", tipo: "comum", ndc: "3", habilidades: [], paginas: [261] },
      {
        papel: "Terno",
        tipo: "especial",
        ndc: "1–2",
        habilidades: ["Fuga Infeliz", "Salve-se Quem Puder"],
        paginas: [261],
      },
      {
        papel: "Continência",
        tipo: "especial",
        ndc: "1–4",
        habilidades: ["Dedo Quente", "Gatilho Furioso", "Zói de Gavião"],
        paginas: [261],
      },
      {
        papel: "Gravata",
        tipo: "especial",
        ndc: "6",
        habilidades: ["Ameaça Covarde", "Escudo Humano", "Mestre Arsenal", "Supremacia"],
        paginas: [261],
      },
    ],
    paginas: [261],
  },
  {
    id: "cabeca-de-abobora",
    emblema: "/story/factions/cabeca-de-abobora.webp",
    nome: "Cabeça de Abóbora",
    categoria: "gangue",
    resumo: "Bando errático de perigo imprevisível.",
    membros: [
      { papel: "Integrantes", tipo: "comum", ndc: "1–6", habilidades: [], paginas: [261] },
    ],
    paginas: [261],
  },
  {
    id: "irmas-gonzaga",
    emblema: "/story/factions/irmas-gonzaga.webp",
    nome: "Irmãs Gonzaga",
    categoria: "gangue",
    resumo: "Quatro irmãs, todas especiais NdC 5.",
    membros: [
      {
        papel: "Rafaela Gonzaga",
        tipo: "especial",
        ndc: "5",
        habilidades: ["Coldre de Sabão", "Parrudeza"],
        habilidadesPendentes: ["Dedo Furioso"],
        paginas: [262],
      },
      {
        papel: "Leonor Gonzaga",
        tipo: "especial",
        ndc: "5",
        habilidades: ["Canção da Emoção", "Livramento", "Zói de Gavião"],
        paginas: [262],
      },
      {
        papel: "Donela Gonzaga",
        tipo: "especial",
        ndc: "5",
        habilidades: ["Às na Manga", "Boca na Botija", "Cuspe e Cola"],
        paginas: [262],
      },
      {
        papel: "Michaela Gonzaga",
        tipo: "especial",
        ndc: "5",
        habilidades: ["Ataque Sacana", "Fumaça na Água", "Galope Certeiro"],
        paginas: [262],
      },
    ],
    paginas: [262],
  },
  {
    id: "gangue-do-cogumelo",
    emblema: "/story/factions/gangue-do-cogumelo.webp",
    nome: "Gangue do Cogumelo",
    categoria: "gangue",
    resumo: "Culto do Sertão de Fungos, chá e alucinações.",
    membros: [
      { papel: "Neófitos", tipo: "comum", ndc: "2", habilidades: [], paginas: [263] },
      { papel: "Elevados", tipo: "comum", ndc: "3", habilidades: [], paginas: [263] },
      {
        papel: "Senescais",
        tipo: "especial",
        ndc: "4–6",
        habilidades: ["Fúria dos Aflitos"],
        habilidadesPendentes: ["Artes Marciais"],
        paginas: [263],
      },
      {
        papel: "Principado",
        tipo: "especial",
        ndc: "6",
        habilidades: ["Ameaça Covarde", "Canção da Emoção", "Supremacia"],
        habilidadesPendentes: ["Artes Marciais"],
        paginas: [263],
      },
    ],
    paginas: [263],
  },
  {
    id: "novos-sagrados",
    emblema: "/story/factions/novos-sagrados.webp",
    nome: "Novos Sagrados",
    categoria: "gangue",
    resumo: "Culto reorganizado em Sacramento pelos novos Bispos (uma habilidade extra expressa, p. 264).",
    membros: [
      { papel: "Seguidores", tipo: "comum", ndc: "1–6", habilidades: [], paginas: [264] },
      {
        papel: "Hermes",
        tipo: "especial",
        ndc: "6",
        habilidades: [
          "Balas Envenenadas",
          "Coldre de Sabão",
          "Dedo Quente",
          "Livramento",
          "Olho Morto",
          "Roubo de Sina",
        ],
        paginas: [264],
      },
      {
        papel: "Abreu",
        tipo: "especial",
        ndc: "5",
        habilidades: [
          "Canção da Emoção",
          "Cuspe e Cola",
          "Escudo Humano",
          "Fuga Infeliz",
          "Supremacia",
        ],
        paginas: [264],
      },
      {
        papel: "Aranha",
        tipo: "especial",
        ndc: "5",
        habilidades: [
          "Ameaça Covarde",
          "Boca na Botija",
          "Chamego",
          "Mestre Arsenal",
          "Zói de Gavião",
        ],
        paginas: [264],
      },
    ],
    paginas: [264],
  },
  {
    id: "policia-bh",
    emblema: "/story/factions/policia-bh.webp",
    nome: "Polícia de Belo Horizonte",
    categoria: "lei",
    resumo: "Força policial da capital; política e corrupção na ambientação não impedem NPC honesto.",
    membros: [
      { papel: "Cabo", tipo: "comum", ndc: "1–2", habilidades: [], paginas: [265] },
      { papel: "Sargento", tipo: "comum", ndc: "1–3", habilidades: [], paginas: [265] },
      { papel: "Tenente", tipo: "comum", ndc: "1–4", habilidades: [], paginas: [265] },
      { papel: "Capitão", tipo: "comum", ndc: "1–6", habilidades: [], paginas: [265] },
      { papel: "Coronel", tipo: "comum", ndc: "1–6", habilidades: [], paginas: [265] },
    ],
    paginas: [265],
  },
  {
    id: "boinas-brancas",
    emblema: "/story/factions/boinas-brancas.webp",
    nome: "Boinas Brancas",
    categoria: "lei",
    resumo: "Segurança ligada às empresas ferroviárias — não é classe de PJ.",
    membros: [
      {
        papel: "Guarda",
        tipo: "especial",
        ndc: "1–2",
        habilidades: ["Gatilho Furioso"],
        paginas: [266],
      },
      {
        papel: "Artilharia",
        tipo: "especial",
        ndc: "3–4",
        habilidades: ["Dedo Quente", "Zói de Gavião"],
        paginas: [266],
      },
    ],
    paginas: [266],
  },
  {
    id: "defesa-nacional",
    emblema: "/story/factions/defesa-nacional.webp",
    nome: "Defesa Nacional",
    categoria: "lei",
    resumo: "Representantes, xerifes e delegados pelo interior. Xerifes nomeados podem ser especiais (ex.: Tonho do Arame, NdC 4 especial, p. 142).",
    membros: [
      { papel: "Representante", tipo: "comum", ndc: "1–2", habilidades: [], paginas: [266] },
      { papel: "Xerife", tipo: "comum", ndc: "1–3", habilidades: [], paginas: [266] },
      { papel: "Delegado", tipo: "comum", ndc: "1–4", habilidades: [], paginas: [266] },
    ],
    paginas: [266],
  },
];
