-- RODAR MANUALMENTE NO SUPABASE SQL EDITOR ANTES DO DEPLOY

ALTER TABLE characters ADD COLUMN IF NOT EXISTS background TEXT;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS subrace TEXT;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS sex TEXT DEFAULT 'male';
ALTER TABLE characters ADD COLUMN IF NOT EXISTS age_category TEXT DEFAULT 'adult';
ALTER TABLE characters ADD COLUMN IF NOT EXISTS alignment TEXT;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS personality JSONB DEFAULT '{}';
ALTER TABLE characters ADD COLUMN IF NOT EXISTS race_traits JSONB DEFAULT '{}';
ALTER TABLE characters ADD COLUMN IF NOT EXISTS class_features JSONB DEFAULT '{}';
ALTER TABLE characters ADD COLUMN IF NOT EXISTS appearance_description TEXT;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS reference_photo_url TEXT;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS avatar_history JSONB DEFAULT '[]';
